;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	View-scroll-page-forward
	View-search-last-regexp-forward
	backward-sexp
	c-electric-brace
	c-electric-colon
	c-electric-paren
	c-electric-semi&comma
	c-electric-slash
	c-electric-star
	c-end-of-statement
	c-indent-line-or-region
	downcase-region
	fill-paragraph
	forward-sexp
	groovy-electric-curlies
	groovy-electric-matching-char
	groovy-electric-pound
	ido-write-file
	indent-for-tab-command
	insert-register
	kill-region
	kill-sexp
	next-multiframe-window
	nxml-electric-slash
	org-beginning-of-line
	org-cycle
	org-end-of-line
	org-force-self-insert
	org-kill-line
	org-self-insert-command
	org-yank
	overwrite-mode
	sgml-slash
	text-scale-decrease
	text-scale-increase
	toggle-truncate-lines
	transpose-sexps
	upcase-region
	wdired-finish-edit
	))

(setq mc/cmds-to-run-once
      '(
	describe-no-warranty
	end-of-buffer
	handle-switch-frame
	make-frame-command
	markdown-exdent-or-delete
	previous-multiframe-window
	run-or-switch-to-shell
	))
